/* ===== BillWatch — provincial data =====
   Each province: { abbr, legislature, session, government, asOf, billsUrl, membersUrl, notes, bills:[...] }
   bill: { num, title, sponsor, status, st:'law'|'move'|'stall', risk:'high'|'medium'|'low'|'positive',
           sum, forr, against, priv, who }
   Nova Scotia is hand-verified. Other provinces are appended from the research agents.
*/
window.PROVINCES_DATA = {
  "Nova Scotia": {
    abbr: "NS",
    legislature: "Nova Scotia House of Assembly",
    session: "65th General Assembly, 1st Session (since Dec 2024)",
    government: "Progressive Conservative majority (42 of 55 seats) under Premier Tim Houston",
    asOf: "June 17, 2026",
    billsUrl: "https://nslegislature.ca/legislative-business/bills-statutes/current-bills",
    membersUrl: "https://nslegislature.ca/members",
    notes: "A fast-moving, high-majority session. The fall 2025 sitting pushed several bills through in days; the spring 2026 sitting ran a record 27 days, passed the budget amid protests over grant cuts, and at one point barred the public from Province House.",
    bills: [
      { num:"Bill 150", title:"Freedom of Information and Protection of Privacy Act", sponsor:"Attorney General / Justice Minister Becky Druhan (PC)", status:"Law — Royal Assent Oct 3, 2025 (in force April 1, 2027)", st:"law", risk:"high",
        sum:"The first rewrite of Nova Scotia's freedom-of-information and privacy law in 25 years — rushed through in about a week, bypassing meaningful committee scrutiny.",
        forr:"Makes the Privacy Commissioner an independent officer of the legislature; modernizes a decades-old statute.",
        against:"The commissioner still cannot issue binding orders (only recommendations); a broad new 'Executive Council records' category walls off cabinet records far beyond traditional confidences; the Centre for Law and Democracy and privacy experts decried the one-week, no-real-hearings process.",
        priv:"This IS the province's core access-to-information and privacy law — more commissioner independence, but weaker public access and a still-toothless watchdog.",
        who:"Anyone who files a freedom-of-information request, journalists, and the public's right to know." },
      { num:"Bill 1", title:"Government Organization and Administration Act (omnibus)", sponsor:"PC government", status:"Law (auditor-general clauses withdrawn)", st:"law", risk:"high",
        sum:"An omnibus bill that originally gave Cabinet the power to fire the Auditor General without cause and to refuse 'frivolous or vexatious' freedom-of-information requests.",
        forr:"Pitched as government 'efficiency' and curbing a handful of very high-volume requesters.",
        against:"The auditor-general firing power triggered province-wide outrage and was withdrawn; critics called it a raw attack on independent oversight and transparency.",
        priv:"Democratic accountability and the public's right to know — watchdog independence and FOI access.",
        who:"Oversight bodies and every citizen who relies on government transparency." },
      { num:"Bill 6", title:"Agriculture, Energy and Natural Resources Act", sponsor:"PC government", status:"Law — effective March 26, 2025", st:"law", risk:"medium",
        sum:"Lifts the 40-plus-year ban on uranium exploration/mining and the 2014 ban on onshore fracking, pitched as resource self-reliance amid U.S. tariffs.",
        forr:"Potential resource revenue, jobs and energy security; allows research into uranium deposits.",
        against:"99 public submissions against, 1 in favour; strong opposition from Mi'kmaq communities, environmental groups and rural residents over water, health and Indigenous rights.",
        priv:"Minimal data-privacy angle; the civil-liberties concern is Indigenous consent (duty to consult) and environmental protection.",
        who:"Rural and Mi'kmaq communities, the environment, the resource sector." },
      { num:"Bill 130", title:"Traffic Safety Act", sponsor:"PC government", status:"Law — Royal Assent Oct 3, 2025 (takes effect 2026)", st:"law", risk:"medium",
        sum:"Replaces the 1930s-era Motor Vehicle Act and, for the first time in Nova Scotia, authorizes photo radar, red-light cameras and intersection cameras.",
        forr:"Overdue modernization; automated enforcement can cut speeding and collisions at dangerous spots.",
        against:"Automated cameras mean routine surveillance of drivers — concerns about data retention, who sees footage, function creep and revenue-driven enforcement.",
        priv:"New automated camera surveillance of drivers — the privacy details live in the 2026 regulations to come.",
        who:"Every driver in Nova Scotia." },
      { num:"Bill 205", title:"Elections Act & House of Assembly Act (amended)", sponsor:"Attorney General / Justice Minister Scott Armstrong (PC)", status:"Law — Royal Assent April 9, 2026", st:"law", risk:"medium",
        sum:"Modernizes elections on the Chief Electoral Officer's recommendations: limited electronic voting, removal of the returning-officer residency rule and the $200 nomination deposit — and it expands who may use the voter roll.",
        forr:"Streamlines elections, widens voting access, and most changes were expert-recommended after the 2021/2024 elections.",
        against:"It broadens permitted uses of the Register of Electors (voter roll) to include soliciting contributions, campaigning and recruiting party members — a real voter-data privacy expansion; e-voting raises security questions.",
        priv:"The province's #2 privacy issue after Bill 150 — more people (parties, candidates, MLAs) can use your voter data for more purposes (incl. fundraising).",
        who:"Every registered voter." },
      { num:"Bill 127", title:"Protecting Nova Scotians Act (omnibus)", sponsor:"PC government", status:"Law — Royal Assent Oct 3, 2025", st:"law", risk:"medium",
        sum:"A controversial omnibus bill that amends the Crown Lands Act (among other statutes), passed quickly during the fall 2025 sitting.",
        forr:"Framed by the government as streamlining and protecting Nova Scotians.",
        against:"Criticized by CBC, the Halifax Examiner and others as a rushed omnibus with resource and rights implications; specific provisions drew pushback.",
        priv:"Limited/uncertain direct privacy angle; the concern is rushed omnibus law-making and Crown-land/resource governance.",
        who:"Crown-land users and, broadly, the public." },
      { num:"Bill 198", title:"Financial Measures (2026) Act", sponsor:"Finance Minister John Lohr (PC)", status:"Law", st:"law", risk:"medium",
        sum:"Enacts Budget 2026-27 and creates a recurring vehicle levy effective Oct 1, 2026: $500 every two years on electric vehicles and $250 on hybrids.",
        forr:"Pitched as road-funding fairness as gas-tax revenue falls; Nova Scotia would be the 4th province to do it.",
        against:"Penalizes cleaner vehicles, adds an affordability hit, and may discourage EV adoption.",
        priv:"Minimal — this is a tax/fiscal measure.",
        who:"Electric-vehicle and hybrid owners." },
      { num:"Bill 193", title:"Powering the Economy Act", sponsor:"PC government", status:"Law — April 9, 2026", st:"law", risk:"low",
        sum:"Secures offshore-wind revenue (a levy of $7,000/MW for the first 10 years), shifts grid responsibilities from Nova Scotia Power to a new IESO Nova Scotia, and creates a Subsurface Energy Resource Extraction Act covering geothermal, natural hydrogen, helium and carbon storage.",
        forr:"Energy modernization, new revenue, and grid-governance reform after Nova Scotia Power's troubles (including a major data breach).",
        against:"Ratepayer-impact and pace-of-change questions.",
        priv:"Minimal.",
        who:"Nova Scotia Power ratepayers and the energy sector." },
      { num:"Bill 11", title:"Administrative Efficiency and Accountability in Healthcare Act", sponsor:"PC government", status:"Law", st:"law", risk:"low",
        sum:"Restructures health-system administration as part of the government's health-care overhaul.",
        forr:"Aims to cut red tape and improve accountability in a strained system.",
        against:"Critics question centralization and whether it improves front-line care.",
        priv:"Watch health-data handling as systems are consolidated.",
        who:"Patients and health-care workers." },
      { num:"Bill 249", title:"Distribution of Fake Intimate Images Act", sponsor:"Suzy Hansen (NDP) — private member's bill", status:"Private member's bill (before the House)", st:"move", risk:"positive",
        sum:"Would amend the Intimate Images and Cyber-protection Act to cover AI-generated and deepfake intimate images.",
        forr:"Closes a real gap as deepfake abuse rises; protects victims.",
        against:"As a private member's bill it is less likely to advance without government support.",
        priv:"Rights-positive — strengthens protection against non-consensual and AI-faked intimate images.",
        who:"Victims of image-based and deepfake abuse." },
      { num:"Bill 131", title:"Privacy and Credit Protection Act", sponsor:"Susan Leblanc (NDP) — private member's bill", status:"Private member's bill (before the House)", st:"move", risk:"positive",
        sum:"Would add consumer data-privacy and credit-protection rights.",
        forr:"Stronger consumer privacy and protection against credit/identity harms.",
        against:"Private member's bills rarely advance under a majority government.",
        priv:"Rights-positive consumer-privacy proposal.",
        who:"Consumers and anyone exposed to data/credit misuse." },
      { num:"Bill 140", title:"Private Data Protection Act", sponsor:"Derek Mombourquette (Liberal) — private member's bill", status:"Private member's bill (before the House)", st:"move", risk:"positive",
        sum:"Would create personal-data protection rights in the private sector provincially.",
        forr:"Fills gaps in provincial private-sector privacy coverage.",
        against:"Unlikely to advance without government backing.",
        priv:"Rights-positive private-sector privacy proposal.",
        who:"Anyone whose data is held by NS businesses." }
    ]
  }
};
